### ISSUE TITLE
No colors/theme for Keywords 

### ISSUE THREAD

**Issue by bsarmento** [AmailP/robot-plugin#120]
Hi,
I reinstalled my project in a new machine and I am trying to get the same colours while using .robot files and the robot framework support plugin: I am not sure what I am missing
This is on the new machine:
[](url)
![Screenshot 2021-09-09 at 13 17 23](https://user-images.githubusercontent.com/17966257/132684190-f3ffe561-0b39-473d-bd25-5c826574691f.png)

This is on the old machine:
![Screenshot 2021-09-09 at 15 02 19](https://user-images.githubusercontent.com/17966257/132700437-327b3263-f096-406f-b6d1-e87e9e62fbf5.png)

Both machines have robot framework support plugin (0.26 on the new one and 0.23 on the old one).
Thanks

**Comment by femarcano** [comment]
This bug is from 0.24 until 0.26. From the delete of showing Highlight in the intelliJ API. 

> 2021-10-03 07:17:30,482 [4340834]  ERROR - aemon.impl.PassExecutorService - Abandoned AnnotationBuilder - its 'create()' method was never called: Builder{message='null', myCurrentElement=SettingName(SettingName), severity=INFORMATION, range=(implicit)(17,30), textAttributes=DEFAULT_INSTANCE_FIELD} 
java.lang.IllegalStateException: Abandoned AnnotationBuilder - its 'create()' method was never called: Builder{message='null', myCurrentElement=SettingName(SettingName), severity=INFORMATION, range=(implicit)(17,30), textAttributes=DEFAULT_INSTANCE_FIELD}
	at com.intellij.codeInsight.daemon.impl.B.assertAnnotationCreated(B.java:341)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.assertAllAnnotationsCreated(AnnotationHolderImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:95)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by AmailP** [comment]
Fixed in #121
