### ISSUE TITLE
No Such Method Error

### ISSUE THREAD

**Issue by gualber98** [AmailP/robot-plugin#15]
I keep getting this error
NoSuchMethodError: com.jetbrains.python.psi.PyClass.getAncestorClasses()Ljava/util/List;

=======================================================================
com.jetbrains.python.psi.PyClass.getAncestorClasses()Ljava/util/List;
java.lang.NoSuchMethodError: com.jetbrains.python.psi.PyClass.getAncestorClasses()Ljava/util/List;
	at amailp.intellij.robot.extensions.RobotLibrariesCompletionContributor$$anon$1.lookupElementsFromMethods$1(RobotLibrariesCompletionContributor.scala:113)
	at amailp.intellij.robot.extensions.RobotLibrariesCompletionContributor$$anon$1.amailp$intellij$robot$extensions$RobotLibrariesCompletionContributor$$anon$$lookupElementsForLibrary$1(RobotLibrariesCompletionContributor.scala:99)
	at amailp.intellij.robot.extensions.RobotLibrariesCompletionContributor$$anon$1$$anonfun$addCompletions$2.apply(RobotLibrariesCompletionContributor.scala:39)
	at amailp.intellij.robot.extensions.RobotLibrariesCompletionContributor$$anon$1$$anonfun$addCompletions$2.apply(RobotLibrariesCompletionContributor.scala:38)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at amailp.intellij.robot.extensions.RobotLibrariesCompletionContributor$$anon$1.addCompletions(RobotLibrariesCompletionContributor.scala:38)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:843)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:825)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:89)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by arunselvarajdb** [comment]
This issue started happening after I updated my pycharm to 5.0.

**Comment by krizex** [comment]
I face the same issue, when I want to install latest version plugin to Pycharm, it says the version is incompatible....So I now use IntelliBot instead of this.

**Comment by AmailP** [comment]
should be fixed now with version 0.13, can you please confirm?
